trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job:  FirstJob
    steps:
    - bash: echo Build First Job
    - bash: echo $(envvar)
    - bash: "echo Build secondjob"
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo Branch name is $(Build.SourceBranchName)
    - bash: echo Source Dir is $(Build.SourcesDirectory)
    - bash: echo Source Branch is$(Build.SourceBranch)
    - bash: echo Default Working dir is $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo echo